import { Button } from "@/components/ui/button";
import { Dialog, DialogContent, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { formatOrderMoney, type CustomerOrder } from "@/lib/mock/orders";

export function ReceiptPreviewDialog({ order, open, onOpenChange, onDownload }: { order: CustomerOrder; open: boolean; onOpenChange: (open: boolean) => void; onDownload: () => void }) {
  if (!order.receipt) return null;
  return <Dialog open={open} onOpenChange={onOpenChange}><DialogContent><DialogHeader><DialogTitle className="capitalize">{order.receipt.type} {order.receipt.number}</DialogTitle></DialogHeader><div className="rounded-xl border border-border bg-background p-5"><div className="border-b border-border pb-4 text-center"><p className="text-sm font-semibold">Zentro</p><p className="mt-1 text-xs text-muted-foreground">Comprobante de venta · Vista de prototipo</p></div><div className="space-y-2 py-4 text-sm"><ReceiptRow label="Pedido" value={order.number} /><ReceiptRow label="Cliente" value={order.customerName} />{order.receipt.customerDocument && <ReceiptRow label="Documento" value={order.receipt.customerDocument} />}{order.receipt.businessName && <ReceiptRow label="Razón social" value={order.receipt.businessName} />}<ReceiptRow label="Fecha" value={new Date(order.receipt.issuedAt).toLocaleString("es-PE")} /></div><div className="space-y-2 border-t border-border pt-4 text-sm"><ReceiptRow label="Subtotal" value={formatOrderMoney(order.subtotal)} />{order.discount > 0 && <ReceiptRow label="Descuento" value={`-${formatOrderMoney(order.discount)}`} />}{order.deliveryFee > 0 && <ReceiptRow label="Envío" value={formatOrderMoney(order.deliveryFee)} />}<div className="flex justify-between pt-2 text-base font-semibold"><span>Total</span><span>{formatOrderMoney(order.total)}</span></div></div></div><DialogFooter><Button variant="outline" onClick={() => onOpenChange(false)}>Cerrar</Button><Button onClick={onDownload}>Descargar</Button></DialogFooter></DialogContent></Dialog>;
}

function ReceiptRow({ label, value }: { label: string; value: string }) { return <div className="flex justify-between gap-4"><span className="text-muted-foreground">{label}</span><span className="text-right font-medium">{value}</span></div>; }
