import { Boxes, PackageCheck, WalletCards } from "lucide-react";
import { StatusBadge } from "@/components/app/shared/StatusBadge";
import type { InventoryBrand } from "@/lib/mock/inventory-brands";
import { BrandActionsMenu } from "./BrandActionsMenu";

interface BrandCardProps { brand: InventoryBrand; onOpen: (brand: InventoryBrand) => void; onEdit: (brand: InventoryBrand) => void; onToggleStatus: (brand: InventoryBrand) => void; onDelete: (brand: InventoryBrand) => void; }

export function BrandCard({ brand, onOpen, onEdit, onToggleStatus, onDelete }: BrandCardProps) {
  return <article className="rounded-xl border border-border bg-card p-4 transition-colors hover:border-primary/25 hover:bg-muted/20"><div className="flex items-center justify-between gap-2"><span className="rounded-md bg-muted px-2.5 py-1 text-xs font-medium text-muted-foreground">{brand.origin}</span><div className="flex items-center gap-1"><StatusBadge status={brand.status} /><BrandActionsMenu brand={brand} onOpen={onOpen} onEdit={onEdit} onToggleStatus={onToggleStatus} onDelete={onDelete} /></div></div><button type="button" onClick={() => onOpen(brand)} className="w-full cursor-pointer text-left"><div className="mt-3 flex items-center gap-3"><span className="flex size-11 shrink-0 items-center justify-center rounded-full bg-primary/12 text-lg font-semibold text-primary ring-1 ring-primary/20">{brand.name.charAt(0)}</span><div className="min-w-0"><h3 className="truncate font-medium">{brand.name}</h3><p className="text-xs text-muted-foreground">Actualizada {new Intl.DateTimeFormat("es-PE", { day: "2-digit", month: "short" }).format(new Date(brand.updatedAt))}</p></div></div><p className="mt-3 line-clamp-2 min-h-10 border-t border-border pt-3 font-sans text-sm text-muted-foreground">{brand.description}</p><div className="mt-3 grid grid-cols-2 gap-x-4 gap-y-2.5 text-sm text-muted-foreground"><span className="flex items-center gap-2"><PackageCheck className="size-3.5" />{brand.productCount} productos</span><span className="flex items-center gap-2"><Boxes className="size-3.5" />{brand.unitsInStock} unidades</span><span className="col-span-2 flex items-center gap-2"><WalletCards className="size-3.5" />S/ {brand.inventoryValue.toLocaleString("es-PE")} valorizados</span></div></button></article>;
}
