"use client";

import { useState } from "react";
import { usePathname, useRouter } from "next/navigation";
import { Ban, Eye, MoreHorizontal, PackageCheck, Pencil, Send, Trash2 } from "lucide-react";
import { ConfirmDialog } from "@/components/app/team/ConfirmDialog";
import { DropdownMenu, DropdownMenuContent, DropdownMenuItem, DropdownMenuSeparator, DropdownMenuTrigger } from "@/components/ui/dropdown-menu";
import { toastMsg } from "@/components/ui/toast-message";
import type { PurchaseOrder } from "@/lib/mock/purchases";
import { usePurchasesStore } from "@/stores/purchases-store";
import { ReceivePurchaseDialog } from "../receptions/ReceivePurchaseDialog";

export function PurchaseActionsMenu({ slug, order }: { slug?: string; order: PurchaseOrder }) {
  const router = useRouter(); const pathname = usePathname(); const resolvedSlug = slug ?? pathname.split("/")[2]; const [receiving, setReceiving] = useState(false); const [confirmation, setConfirmation] = useState<"cancel" | "delete" | null>(null); const setStatus = usePurchasesStore((state) => state.setStatus); const removeOrder = usePurchasesStore((state) => state.removeOrder); const href = `/app/${resolvedSlug}/compras/${order.id}`;
  const execute = () => { if (confirmation === "cancel") { setStatus(order.id, "cancelada"); toastMsg.info("Orden cancelada", `${order.number} ya no admite recepciones.`); } if (confirmation === "delete") { removeOrder(order.id); toastMsg.info("Borrador eliminado", `${order.number} se eliminó del prototipo.`); } setConfirmation(null); };
  return <><DropdownMenu><DropdownMenuTrigger onClick={(event) => event.stopPropagation()} className="cursor-pointer rounded-lg p-1.5 text-muted-foreground hover:bg-accent hover:text-foreground" aria-label={`Acciones de ${order.number}`}><MoreHorizontal className="size-4" /></DropdownMenuTrigger><DropdownMenuContent align="end" className="w-52 font-heading" onClick={(event) => event.stopPropagation()}><DropdownMenuItem onClick={() => router.push(href)} className="cursor-pointer gap-2"><Eye className="size-4" />Ver detalle</DropdownMenuItem>{order.status === "borrador" && <><DropdownMenuItem onClick={() => router.push(`${href}/editar`)} className="cursor-pointer gap-2"><Pencil className="size-4" />Editar</DropdownMenuItem><DropdownMenuItem onClick={() => { setStatus(order.id, "enviada"); toastMsg.success("Orden enviada", `${order.number} quedó pendiente de recepción.`); }} className="cursor-pointer gap-2"><Send className="size-4" />Enviar orden</DropdownMenuItem><DropdownMenuSeparator /><DropdownMenuItem variant="destructive" onClick={() => setConfirmation("delete")} className="cursor-pointer gap-2"><Trash2 className="size-4" />Eliminar borrador</DropdownMenuItem></>}{(["enviada", "parcial"] as string[]).includes(order.status) && <><DropdownMenuItem onClick={() => setReceiving(true)} className="cursor-pointer gap-2"><PackageCheck className="size-4" />Registrar recepción</DropdownMenuItem>{order.receivedUnits === 0 && <><DropdownMenuSeparator /><DropdownMenuItem variant="destructive" onClick={() => setConfirmation("cancel")} className="cursor-pointer gap-2"><Ban className="size-4" />Cancelar orden</DropdownMenuItem></>}</>}</DropdownMenuContent></DropdownMenu><ReceivePurchaseDialog order={order} open={receiving} onOpenChange={setReceiving} /><ConfirmDialog open={Boolean(confirmation)} onOpenChange={(open) => !open && setConfirmation(null)} title={confirmation === "delete" ? "Eliminar borrador" : "Cancelar orden"} description={confirmation === "delete" ? `¿Deseas eliminar ${order.number}?` : `${order.number} quedará cerrada y no admitirá recepciones.`} confirmLabel={confirmation === "delete" ? "Eliminar" : "Cancelar orden"} onConfirm={execute} /></>;
}
