import { CalendarDays, Clock3, MapPin, UserRound, Wallet } from "lucide-react";
import { StatusBadge } from "@/components/app/shared/StatusBadge";
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { agendaMoney, appointmentModalityLabel, appointmentPaymentLabel, type Appointment } from "@/lib/mock/agenda";

export function AppointmentPreviewDialog({ appointment, open, onOpenChange }: { appointment: Appointment | null; open: boolean; onOpenChange: (open: boolean) => void }) {
  if (!appointment) return null;
  const date = new Intl.DateTimeFormat("es-PE", { dateStyle: "full", timeStyle: "short" }).format(new Date(appointment.startsAt));
  return <Dialog open={open} onOpenChange={onOpenChange}><DialogContent className="sm:max-w-lg"><DialogHeader><div className="flex items-center gap-2"><StatusBadge status={appointment.status} /><span className="text-xs text-muted-foreground">{appointment.number}</span></div><DialogTitle className="pt-2">{appointment.serviceName}</DialogTitle><DialogDescription>{appointment.customerName}</DialogDescription></DialogHeader><dl className="grid gap-4 rounded-xl border bg-muted/20 p-4 sm:grid-cols-2"><div><dt className="flex items-center gap-2 text-xs text-muted-foreground"><CalendarDays className="size-3.5" />Fecha</dt><dd className="mt-1 text-sm font-medium capitalize">{date}</dd></div><div><dt className="flex items-center gap-2 text-xs text-muted-foreground"><Clock3 className="size-3.5" />Duración</dt><dd className="mt-1 text-sm font-medium">{appointment.durationMinutes} minutos</dd></div><div><dt className="flex items-center gap-2 text-xs text-muted-foreground"><UserRound className="size-3.5" />Responsable</dt><dd className="mt-1 text-sm font-medium">{appointment.responsibleName ?? "Por asignar"}</dd></div><div><dt className="flex items-center gap-2 text-xs text-muted-foreground"><MapPin className="size-3.5" />Atención</dt><dd className="mt-1 text-sm font-medium">{appointment.locationName ?? appointmentModalityLabel(appointment.modality)}</dd></div><div className="sm:col-span-2"><dt className="flex items-center gap-2 text-xs text-muted-foreground"><Wallet className="size-3.5" />Cobro</dt><dd className="mt-1 text-sm font-medium">{appointmentPaymentLabel(appointment.paymentStatus)} · {agendaMoney(appointment.paidAmount)} de {agendaMoney(appointment.price)}</dd></div></dl>{appointment.notes && <p className="rounded-lg bg-muted p-3 text-sm text-muted-foreground">{appointment.notes}</p>}</DialogContent></Dialog>;
}
