import { DateTimePicker } from "@/components/ui/date-time-picker";
import { Input } from "@/components/ui/input";
import { Switch } from "@/components/ui/switch";
import { Field, FormSection } from "./FormSection";
import type { PromotionFormValues } from "./types";

export function PromotionConfiguration({ values, errors, onChange }: { values: PromotionFormValues; errors: Record<string, string>; onChange: (field: keyof PromotionFormValues, value: string | boolean) => void }) {
  return <div className="flex flex-col gap-5"><FormSection title="Vigencia" description="Define cuándo comienza y termina el beneficio."><div className="grid gap-5 md:grid-cols-2 xl:grid-cols-1"><Field label="Fecha de inicio" error={errors.startsAt}><DateTimePicker value={values.startsAt} onChange={(value) => onChange("startsAt", value)} placeholder="Seleccionar inicio" /></Field><Field label="Fecha de finalización" error={errors.endsAt}><DateTimePicker value={values.endsAt} onChange={(value) => onChange("endsAt", value)} placeholder="Seleccionar finalización" /></Field></div></FormSection><FormSection title="Uso y prioridad" description="Controla la disponibilidad total y los conflictos con otras promociones."><div className="grid gap-5"><Field label="Límite de clientes"><label className="flex cursor-pointer items-center justify-between rounded-lg border border-border px-4 py-2.5"><span className="font-normal text-muted-foreground">Uso ilimitado</span><Switch checked={values.unlimitedUsage} onCheckedChange={(checked) => onChange("unlimitedUsage", checked)} /></label></Field>{!values.unlimitedUsage && <Field label="Total de usos disponibles" error={errors.usageLimit}><Input type="number" min={1} value={values.usageLimit} onChange={(event) => onChange("usageLimit", event.target.value)} placeholder="Ej. 100" className="h-fit rounded-lg px-4 py-2" /></Field>}<Field label="Prioridad" hint="Un número mayor tendrá preferencia si existen conflictos." error={errors.priority}><Input type="number" min={1} value={values.priority} onChange={(event) => onChange("priority", event.target.value)} placeholder="Ej. 10" className="h-fit rounded-lg px-4 py-2" /></Field></div></FormSection></div>;
}
